// <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inf="http://inf.soap.tlexc.custom.go.th/">
// <soapenv:Header/>
// <soapenv:Body>
//    <inf:getNoticeListNoticeByConAdv>
//       <!--Optional:-->
//       <arg0>
//          <!--Optional:-->
//          <noticeCode>?</noticeCode>
//          <!--Optional:-->
//          <noticeDate>?</noticeDate>
//          <!--Optional:-->
//          <staffNameReceiv>?</staffNameReceiv>
//          <!--Optional:-->
//          <departmentNameReceive>?</departmentNameReceive>
//          <!--Optional:-->
//          <noticeDueDate>?</noticeDueDate>
//          <!--Optional:-->
//          <groupName>?</groupName>
//          <!--Optional:-->
//          <firstName>?</firstName>
//          <!--Optional:-->
//          <titleName>?</titleName>
//          <!--Optional:-->
//          <lastName>?</lastName>
//       </arg0>
//    </inf:getNoticeListNoticeByConAdv>
// </soapenv:Body>
// </soapenv:Envelope>