// <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inf="http://inf.soap.tlexc.custom.go.th/">
// <soapenv:Header/>
// <soapenv:Body>
//    <inf:insNoticeNoticeAll>
//       <!--Optional:-->
//       <arg0>
//          <!--Optional:-->
//          <notice>
//             <!--Optional:-->
//             <arrestDesc>?</arrestDesc>
//             <!--Optional:-->
//             <createBy>?</createBy>
//             <!--Optional:-->
//             <departmentNameCommander>?</departmentNameCommander>
//             <!--Optional:-->
//             <departmentNameReceive>?</departmentNameReceive>
//             <!--Optional:-->
//             <informType>?</informType>
//             <!--Optional:-->
//             <noticeCode>?</noticeCode>
//             <!--Optional:-->
//             <noticeDate>?</noticeDate>
//             <!--Optional:-->
//             <noticeDueDate>?</noticeDueDate>
//             <!--Optional:-->
//             <noticeStation>?</noticeStation>
//             <!--Optional:-->
//             <noticeTime>?</noticeTime>
//             <!--Optional:-->
//             <positionNameReceive>?</positionNameReceive>
//             <!--Optional:-->
//             <remarks>?</remarks>
//             <!--Optional:-->
//             <secretLevel>?</secretLevel>
//             <!--Optional:-->
//             <staffNameAccept>?</staffNameAccept>
//             <!--Optional:-->
//             <staffNameReceive>?</staffNameReceive>
//          </notice>
//       </arg0>
//    </inf:insNoticeNoticeAll>
// </soapenv:Body>
// </soapenv:Envelope>