// <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inf="http://inf.soap.tlexc.custom.go.th/">
// <soapenv:Header/>
// <soapenv:Body>
//    <inf:insNoticeLocationAll>
//       <!--Optional:-->
//       <arg0>
//          <!--Optional:-->
//          <location>
//             <!--Optional:-->
//             <address>?</address>
//             <!--Optional:-->
//             <alley>?</alley>
//             <!--Optional:-->
//             <building>?</building>
//             <!--Optional:-->
//             <coodinateX>?</coodinateX>
//             <!--Optional:-->
//             <coodinateY>?</coodinateY>
//             <!--Optional:-->
//             <createdBy>?</createdBy>
//             <!--Optional:-->
//             <floor>?</floor>
//             <!--Optional:-->
//             <lawsuitCode>?</lawsuitCode>
//             <!--Optional:-->
//             <locationId>?</locationId>
//             <!--Optional:-->
//             <locationName>?</locationName>
//             <!--Optional:-->
//             <noticeCode>?</noticeCode>
//             <!--Optional:-->
//             <policeStation>?</policeStation>
//             <!--Optional:-->
//             <road>?</road>
//             <!--Optional:-->
//             <room>?</room>
//             <!--Optional:-->
//             <subdistrictCode>?</subdistrictCode>
//             <!--Optional:-->
//             <village>?</village>
//          </location>
//       </arg0>
//    </inf:insNoticeLocationAll>
// </soapenv:Body>
// </soapenv:Envelope>